import ts from 'typescript';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';import {unzipSync,strFromU8} from 'fflate';
await mkdir('.sites-runtime/export-tests',{recursive:true});let source=await readFile('lib/analytics-export.ts','utf8');await writeFile('.sites-runtime/export-tests/export.mjs',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);const {csv,sheets,xlsx,exportDataset}=await import('../.sites-runtime/export-tests/export.mjs');
const record={id:'safe',name:'=HYPERLINK("x")',created:'2026-02-01',date:'2026-02-02',createdAt:'2026-02-01T12:00:00Z',startsAt:'2026-02-02T18:00:00-03:00',closer:'Karina',former:true,formerLabel:'Antiga membra',attribution:'verified',reviewReason:'',cancelled:false};const data={records:[record,{...record,id:'second',closer:'Revisão',attribution:'review',date:'2026-03-02'}],coverage:{complete:true,personalConnected:false,accounts:['company@example.com'],authorAccounts:['company@example.com']}};
const d=exportDataset(data,'2026-01-01','2026-02-28','creation','all');assert.equal(d.total,2);assert.equal(d.filters.from,'2026-02-01');assert.equal(d.ranking[0].count,1);assert.equal(d.review,1);assert.equal(d.months.length,1);assert.equal(d.months[0].month,'2026-02');assert.equal(d.months[0].count,2);assert.equal(d.partial,true);
const january={...record,id:'january',created:'2026-01-31',date:'2026-01-31'};assert.equal(exportDataset({...data,records:[january]},'2026-01-01','2026-01-31','creation','all').total,0);assert.equal(exportDataset({...data,records:[january]},'2026-01-01','2026-01-31','meeting','all').total,0);
assert.equal(exportDataset(data,'2026-02-01','2026-02-28','meeting','all').total,1);assert.equal(exportDataset(data,'2026-01-01','2026-02-28','creation','current').total,0);
const tabs=sheets(d),text=csv(tabs[0].rows);assert.ok(text.startsWith('\uFEFF'));assert.ok(text.includes("'=HYPERLINK"));assert.ok(text.includes('2026-02-01 09:00:00'));assert.ok(text.includes('Antiga membra'));
const zipped=xlsx(tabs),files=unzipSync(zipped);assert.equal(Object.keys(files).filter(x=>x.startsWith('xl/worksheets')).length,4);assert.ok(strFromU8(files['xl/worksheets/sheet1.xml']).includes('t="inlineStr"'));assert.ok(!strFromU8(files['xl/worksheets/sheet1.xml']).includes('<f>'));assert.ok(strFromU8(files['xl/workbook.xml']).includes('Metodologia'));
await writeFile('.sites-runtime/export-tests/verified.xlsx',zipped);console.log('Passed: filtered exports, ambiguity exclusion from ranking, partial coverage, São Paulo timestamps, CSV escaping/formula protection, genuine four-sheet XLSX and strings without executable formulas.');

const multi=exportDataset({...data,records:[{...record,former:false,credits:[{name:'Karina',former:true,formerLabel:'Antiga membra'},{name:'Luccas',former:false,formerLabel:'Antigo membro'}]}]},'2026-01-01','2026-02-28','creation','all');assert.equal(multi.total,1);assert.equal(multi.ranking.length,2);assert.equal(multi.ranking.reduce((n,r)=>n+r.count,0),2);
const formerOnly=exportDataset({...data,records:[{...record,former:false,credits:[{name:'Karina',former:true,formerLabel:'Antiga membra'},{name:'Luccas',former:false,formerLabel:'Antigo membro'}]}]},'2026-01-01','2026-02-28','creation','former');assert.equal(formerOnly.total,1);assert.equal(formerOnly.ranking.length,1);assert.equal(formerOnly.ranking[0].closer,'Karina');

const gap=exportDataset({...data,records:[],coverage:{...data.coverage,personalConnected:true,sourceMonths:[{month:'2026-08',created:10,meetings:9}]}},'2026-08-01','2026-08-31','creation','all');assert.equal(gap.months[0].count,0);assert.match(gap.months[0].coverage,/Nenhum novo lead/);
