import {requireChatGPTUser,chatGPTSignOutPath} from '@/app/chatgpt-auth';
import {one} from '@/db/raw';
import {Button,ButtonLink} from '@openai/apps-sdk-ui/components/Button';
import {Badge} from '@openai/apps-sdk-ui/components/Badge';
import {Alert} from '@openai/apps-sdk-ui/components/Alert';
export const dynamic='force-dynamic';
export default async function Access(){
 const user=await requireChatGPTUser('/acesso');
 let connected=false,unavailable=false;
 try{connected=(await one<{status:string}>("SELECT status FROM google_accounts WHERE owner=? AND status='connected' LIMIT 1",user.userId))?.status==='connected'}catch{unavailable=true}
 return <main className="min-h-dvh flex items-center justify-center p-5 bg-surface"><section className="w-full max-w-lg rounded-3xl border border-default bg-surface p-6 md:p-10 space-y-7"><header className="space-y-3"><img src="/hod-logo.svg" width="64" height="64" alt="Logo HOD Hub"/><Badge color="info">Acesso privado</Badge><p className="text-sm font-semibold text-secondary">HOME OFFICE DIGITAL</p><h1 className="heading-2xl">Seu HOD Hub.</h1><p className="text-secondary">Sua operação de consultorias, de onde você estiver.</p></header><div className="rounded-2xl border border-default p-4 space-y-2"><p className="text-sm text-secondary">Você entrou como</p><p className="font-semibold break-words">{user.displayName}</p><p className="text-sm text-secondary break-all">{user.email}</p></div><div className="space-y-3"><div className="flex items-center justify-between gap-3"><h2 className="heading-sm">Google Agenda</h2><Badge color={connected?'success':'warning'}>{connected?'Conectado':'Conexão necessária'}</Badge></div><p className="text-sm text-secondary">{connected?'Sua autorização está salva no servidor. Abra o aplicativo no celular ou computador sem conectar o Google a cada visita.':'Conecte suas agendas para carregar as consultorias. Esta autorização é independente do acesso ao aplicativo.'}</p>{unavailable&&<Alert color="warning" variant="soft" description="Não foi possível verificar a conexão agora. Você pode entrar e tentar novamente nas configurações."/>}{!connected&&!unavailable&&<form action="/api/google/start" method="post"><Button type="submit" color="primary" block>Conectar Google Agenda</Button></form>}</div><div className="space-y-3"><ButtonLink href="/" color="primary" block>Entrar no HOD Hub</ButtonLink><ButtonLink href="/?pagina=configuracoes" variant="outline" color="secondary" block>Gerenciar conexão e agendas</ButtonLink></div><footer className="text-xs text-secondary space-y-3"><p>Abra este endereço no Safari ou Chrome. Em um novo aparelho, o Sites pode pedir que você entre com sua conta do ChatGPT.</p><a className="underline" href={chatGPTSignOutPath('/acesso')} target="_top">Sair desta conta</a></footer></section></main>
}
