import {writer} from '@/lib/api';import {failure,noStore,ProofError} from '@/lib/google-proof';import {database,one} from '@/db/raw';import {states} from '@/lib/demo';
export const dynamic='force-dynamic';
export async function POST(r:Request){try{const u=await writer(r),b=await r.json() as {id:string;status?:string;note?:string;revision:number;requestId:string};if(!/^[a-f0-9]{64}$/.test(b.id)||!Number.isInteger(b.revision)||!b.requestId||b.requestId.length>100||((b.status===undefined)===(b.note===undefined))||b.status!==undefined&&!states.includes(b.status as typeof states[number])||b.note!==undefined&&(typeof b.note!=='string'||b.note.length>10000))throw new ProofError(400,'invalid_request','Confira os campos e tente novamente.');
 if(!await one('SELECT canonical_id FROM google_events WHERE owner=? AND canonical_id=? AND kind<>\'other\' LIMIT 1',u.userId,b.id))throw new ProofError(404,'not_found','Consultoria não encontrada.');
 if(await one('SELECT id FROM operational_history WHERE owner=? AND request_id=?',u.userId,b.requestId))return Response.json({status:'success'},{headers:noStore});
 const action=b.status!==undefined?'status':'note',value=b.status??b.note!;const d=database();
 // Atomic revision comparison plus history INSERT...SELECT prevents lost updates and records no history on conflict.
 const result=await d.batch([d.prepare('INSERT INTO operational(owner,id,revision) VALUES(?,?,0) ON CONFLICT(owner,id) DO NOTHING').bind(u.userId,b.id),d.prepare(`UPDATE operational SET ${action}=?,revision=revision+1 WHERE owner=? AND id=? AND revision=?`).bind(value,u.userId,b.id,b.revision),d.prepare('INSERT INTO operational_history(id,owner,consultation_id,at,action,value,request_id) SELECT ?,?,?,?,?,?,? WHERE changes()=1 AND EXISTS(SELECT 1 FROM operational WHERE owner=? AND id=? AND revision=?)').bind(crypto.randomUUID(),u.userId,b.id,new Date().toISOString(),action,value,b.requestId,u.userId,b.id,b.revision+1)]);
 if(!result[1].meta.changes)throw new ProofError(409,'conflict','Este registro mudou em outra sessão. Atualize antes de salvar.');return Response.json({status:'success',revision:b.revision+1},{headers:noStore})}catch(e){return failure(e)}}
