 'use client';
import {useEffect,useState} from 'react';
import {DateTime} from 'luxon';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Input} from '@openai/apps-sdk-ui/components/Input';
import {Badge} from '@openai/apps-sdk-ui/components/Badge';
import {Avatar} from '@openai/apps-sdk-ui/components/Avatar';
import {SegmentedControl} from '@openai/apps-sdk-ui/components/SegmentedControl';
import {DateRangePicker} from '@openai/apps-sdk-ui/components/DateRangePicker';
import {Checkbox} from '@openai/apps-sdk-ui/components/Checkbox';
import {Switch} from '@openai/apps-sdk-ui/components/Switch';
import {RadioGroup} from '@openai/apps-sdk-ui/components/RadioGroup';
import {Alert} from '@openai/apps-sdk-ui/components/Alert';
import {EmptyMessage} from '@openai/apps-sdk-ui/components/EmptyMessage';
import {Popover} from '@openai/apps-sdk-ui/components/Popover';
import {Search,Download,ArrowUpRight,Calendar,InfoCircle} from '@openai/apps-sdk-ui/components/Icon';
import {postApi,type HubData} from '@/lib/hub-types';
import {LiveSettings} from './live-settings';
import {useMotion,MotionSwap,MotionReveal} from './apps-motion';
import {Panel,Choice,StatusBadge,type ThemePreference} from './apps-primitives';
import type {Consultation} from '@/lib/demo';
function Empty({title,description}:{title:string;description:string}){return <EmptyMessage><EmptyMessage.Icon><Calendar/></EmptyMessage.Icon><EmptyMessage.Title>{title}</EmptyMessage.Title><EmptyMessage.Description>{description}</EmptyMessage.Description></EmptyMessage>}
function Segments({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div className="max-w-full overflow-x-auto"><SegmentedControl aria-label={label} value={value} onChange={onChange} size="lg">{options.map(o=><SegmentedControl.Option key={o} value={o}>{o}</SegmentedControl.Option>)}</SegmentedControl></div>}
function Heading({title,description,children}:{title:string;description?:string;children?:React.ReactNode}){return <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="heading-sm">{title}</h2>{description&&<p className="text-sm text-secondary mt-1">{description}</p>}</div>{children}</div>}
function Metric({label,value,description}:{label:string;value:string|number;description:string}){return <Panel><p className="text-sm text-secondary">{label}</p><p className="heading-xl mt-3 tabular-nums">{value}</p><p className="text-xs text-secondary mt-2">{description}</p></Panel>}
function Track({value,max,label}:{value:number;max:number;label:string}){return <div role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={max} aria-valuenow={value} className="h-2 rounded-full bg-surface-tertiary overflow-hidden"><div className="hod-meter-fill h-full rounded-full bg-info-solid" style={{transform:`scaleX(${max?Math.min(1,value/max):0})`}}/></div>}
export default function AppsSecondaryPages({page,date,rows,empty=false,openDetail,notify,theme,setTheme,onPhonesChange,data,reload,sync}:{data:HubData|null;reload:()=>Promise<void>;sync:()=>void;page:string;date:string;rows:Consultation[];empty?:boolean;openDetail:(c:Consultation)=>void;notify:(s:string)=>void;theme:ThemePreference;setTheme:(s:ThemePreference)=>void;onPhonesChange:(v:boolean)=>void}){
const [freeCloser,setFreeCloser]=useState('Todos');const [period,setPeriod]=useState('Todos');const [onlyFree,setOnlyFree]=useState(true);const [freeView,setFreeView]=useState('Janelas');
const [summaryType,setSummaryType]=useState('Todos');const [summarySearch,setSummarySearch]=useState('');
const [range,setRange]=useState('30 dias');const [from,setFrom]=useState(DateTime.fromISO(date,{zone:'America/Sao_Paulo'}).minus({days:29}).toISODate()!);const [to,setTo]=useState(date);const [dimension,setDimension]=useState('Data da reunião');const [historyFilter,setHistoryFilter]=useState('Todos');
const [settingsTab,setSettingsTab]=useState('Geral');const [duration,setDuration]=useState('50');const [density,setDensity]=useState('Confortável');const [showPhones,setShowPhones]=useState(true);const {reduced:reduceMotion,preference:motionPreference,setPreference:setMotionPreference}=useMotion();const [selectedCalendars,setCalendars]=useState<string[]>([]);const [syncFrequency,setSyncFrequency]=useState('Manual');const [saved,setSaved]=useState(false);
function past(c:Consultation){return DateTime.fromISO(c.endsAt||`${c.date}T${c.time}`,{zone:'America/Sao_Paulo'}).plus({minutes:c.endsAt?0:c.duration}).toMillis()<Date.now()}
useEffect(()=>{if(data?.preferences){setDuration(data.preferences.duration||'50');setDensity(data.preferences.density||'Confortável');setShowPhones(data.preferences.showPhones!==false)}},[data?.preferences]);
const liveTeam=(data?.calendars||[]).filter(c=>c.selected&&c.team_status==='active'&&c.closer!=='Rafael').map(c=>({name:c.closer,color:''}));
const dayRows=rows.filter(c=>c.date===date);
const summary=data?.dailySummary;
const createdIds=new Set(summary?.ids.created||[]),meetingIds=new Set(summary?.ids.meetings||[]);
const sourceRows=rows.filter(c=>createdIds.has(c.id)||meetingIds.has(c.id));
const summaryRows=sourceRows.filter(c=>(summaryType==='Todos'||(summaryType==='Qualificados'&&createdIds.has(c.id)&&c.qualified)||(summaryType==='Reagendamentos'&&createdIds.has(c.id)&&c.rescheduled)||(summaryType==='Agendamentos'&&meetingIds.has(c.id))||(summaryType==='Não passadas'&&summary?.ids.notPassed.includes(c.id))||(summaryType==='No-show'&&summary?.ids.noShow.includes(c.id))||(summaryType==='Passadas'&&summary?.ids.past.includes(c.id)))&&`${c.name} ${c.closer}`.toLocaleLowerCase('pt-BR').includes(summarySearch.toLocaleLowerCase('pt-BR'))).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)||a.id.localeCompare(b.id));
const slots=(data?.availability||[]).filter(s=>period==='Todos'||(period==='Manhã'&&s.h<12)||(period==='Tarde'&&s.h>=12&&s.h<18)||(period==='Noite'&&s.h>=18)).map(s=>freeCloser==='Todos'?s:{...s,available:s.available.filter(t=>t.name===freeCloser),capacity:s.reliable?.includes(freeCloser)?1:0,occupied:s.reliable?.includes(freeCloser)&&!s.available.some(t=>t.name===freeCloser)?1:0}).filter(s=>!onlyFree||s.available.length);
const aggregate=(data?.analyticsRecords||[]).filter(c=>dimension!=='Data da criação'||c.creationRecord);
const analytics=aggregate.filter(c=>{const d=dimension==='Data da criação'?c.created:c.date;let start=from,end=to;if(range==='7 dias'||range==='30 dias'){end=date;const beginning=new Date(date+'T12:00:00-03:00');beginning.setUTCDate(beginning.getUTCDate()-(range==='7 dias'?6:29));start=beginning.toISOString().slice(0,10);}if(range==='Todo histórico'){start='0000-01-01';end='9999-12-31'}return d>=start&&d<=end&&(historyFilter==='Todos'||(historyFilter==='Atuais'&&!c.former)||(historyFilter==='Antigos'&&c.former))});
const ranking=Array.from(new Set(analytics.map(c=>c.closer))).map(n=>({name:n,count:analytics.filter(c=>c.closer===n).length,color:analytics.find(c=>c.closer===n)!.color,former:analytics.find(c=>c.closer===n)!.former})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
const hourVolume=Array.from({length:15},(_,i)=>i+8).map(h=>({hour:`${String(h).padStart(2,'0')}:00`,count:analytics.filter(c=>Number(c.time.slice(0,2))===h).length}));
async function savePreferences(){try{await postApi('/api/preferences',{duration,density,showPhones});document.documentElement.dataset.density=density==='Compacta'?'compact':'comfortable';onPhonesChange(showPhones);setSaved(true);notify('Preferências salvas no servidor');await reload()}catch(e){notify((e as Error).message)}}

const imported=Boolean(data?.calendars.some(c=>c.last_sync));
const counts=analytics.reduce<Record<string,number>>((a,c)=>{const d=dimension==='Data da reunião'?c.date:c.created;a[d]=(a[d]||0)+1;return a},{});
const orderedDays=Object.entries(counts).sort((a,b)=>a[0].localeCompare(b[0]));
function exportSummary(){const escape=(v:string)=>'"'+v.replaceAll('"','""')+'"';const lines=['Nome,Closer,Criação (America/Sao_Paulo),Reunião (America/Sao_Paulo),Classificação,Situação',...summaryRows.map(c=>[c.name,c.closer,DateTime.fromISO(c.createdAt,{zone:'America/Sao_Paulo'}).toFormat('dd/MM/yyyy HH:mm:ss'),DateTime.fromISO(c.startsAt||'',{zone:'America/Sao_Paulo'}).toFormat('dd/MM/yyyy HH:mm'),c.qualified?'Qualificado':c.rescheduled?'Reagendamento':'Reunião comercial',c.status].map(escape).join(','))];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=`hod-hub-${date}.csv`;a.click();URL.revokeObjectURL(url);notify('Exportação concluída')}
if(empty&&page!=='Configurações')return <Empty title="Nenhum registro disponível" description="Nenhum registro sincronizado nesta data."/>;
return <MotionSwap identity={page} className="space-y-6">{page==='Horários Livres'?<>
<Alert variant="soft" color="info" title="Disponibilidade das agendas" description="Expediente 08:00–23:00 · janelas de 1 hora. Todos os compromissos bloqueantes são considerados. Agendas incompletas não entram na capacidade disponível."/>
<Panel className="flex flex-wrap gap-4 items-end"><div className="w-52"><Choice label="Closer" id="free-closer" value={freeCloser} options={['Todos',...liveTeam.map(t=>t.name)]} onChange={setFreeCloser}/></div><Segments label="Período disponível" value={period} options={['Todos','Manhã','Tarde','Noite']} onChange={setPeriod}/><Checkbox label="Só com vagas" checked={onlyFree} onCheckedChange={setOnlyFree}/></Panel>
<Heading title={`${slots.length} janelas disponíveis`} description="Somente agendas selecionadas com leitura concluída"><Segments label="Visualização de disponibilidade" value={freeView} options={['Janelas','Por closer']} onChange={setFreeView}/></Heading>
<MotionSwap identity={freeView+period+freeCloser+onlyFree}>{!slots.length?<Empty title="Nenhuma janela neste filtro" description="Altere o closer, o período ou a opção de vagas."/>:freeView==='Janelas'?<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{slots.map(s=><Panel key={s.h} className="space-y-4"><Heading title={`${s.start} – ${s.end}`}><Badge color={s.available.length?'success':'secondary'}>{s.available.length} vagas</Badge></Heading><Track value={s.occupied} max={s.capacity} label={`Ocupação ${s.start}`}/><p className="text-xs text-secondary">{s.occupied} ocupados · capacidade {s.capacity}</p><div className="flex flex-wrap gap-2">{s.available.map(t=><Badge color="discovery" key={t.name}>{t.name}</Badge>)}</div>{!s.available.length&&<p className="text-sm text-secondary">Todos os closers estão ocupados.</p>}<Popover><Popover.Trigger><Button color="primary" variant="ghost" opticallyAlign="start">Ver janela<ArrowUpRight/></Button></Popover.Trigger><Popover.Content minWidth="auto" width={270}><div className="p-4 space-y-3"><h3 className="heading-xs">{s.start} – {s.end}</h3><p className="text-sm">{s.available.length} vagas</p><p className="text-xs text-secondary">Janela calculada a partir dos compromissos do Google Agenda.</p></div></Popover.Content></Popover></Panel>)}</div>:<div className="grid sm:grid-cols-2 gap-4">{liveTeam.filter(t=>freeCloser==='Todos'||t.name===freeCloser).map(t=><Panel key={t.name} className="space-y-4"><Heading title={t.name}><Badge>{slots.filter(s=>s.available.some(a=>a.name===t.name)).length} janelas</Badge></Heading><div className="flex flex-wrap gap-2">{slots.filter(s=>s.available.some(a=>a.name===t.name)).map(s=><Button key={s.h} color="primary" variant="outline" size="sm" onClick={()=>notify(`${t.name}: ${s.start}–${s.end}, disponibilidade na agenda`)}>{s.start}</Button>)}</div></Panel>)}</div>}</MotionSwap>
<Alert variant="soft" color="info" description="Over é separado da capacidade dos closers. Agendas indisponíveis não são consideradas livres."/>
</>:page==='Resumo Diário'?<>
<Alert variant="soft" color="info" title="Resumo da operação" description="Agendamentos são as consultorias marcadas para esta data. Qualificados e reagendamentos usam a criação no dia: primeiro nome no histórico disponível ou nome já visto. Passadas estão na agenda de outro closer, independentemente do horário; no Rafael, não passadas. No-show conta somente evento riscado no Google Agenda."/>
<p className="text-xs text-secondary">{data?.historyCoverage}</p>
{summary&&!summary.complete&&<Alert variant="soft" color="warning" title="Resumo parcial" description="A leitura de todas as agendas precisa estar concluída para validar novos nomes e totais. Os registros abaixo são os disponíveis."/>}
<div className="grid grid-cols-2 lg:grid-cols-3 gap-4">{[['Agendamentos',summary?.counts.appointments,'Consultorias marcadas para esta data'],['Qualificados',summary?.counts.qualified,'Nomes novos criados no dia'],['Reagendamentos',summary?.counts.rescheduled,'Novas criações de nomes já vistos'],['Passadas',summary?.counts.past,'Na agenda de outro closer, sem depender do horário'],['Não passadas',summary?.counts.notPassed,'Permanecem no Rafael ou sem closer identificado'],['No-show',summary?.counts.noShow,'Consultorias da data riscadas no Google Agenda']].map(([label,value,description])=><Metric key={String(label)} label={String(label)} value={summary?.complete?Number(value):'—'} description={String(description)}/>)}</div>
<Panel className="space-y-5"><Heading title="Resumo Diário" description={`${summaryRows.length} registros no filtro`}><Button color="primary" variant="outline" onClick={exportSummary}><Download/>Exportar</Button></Heading><div className="flex flex-wrap gap-4 items-end"><div className="flex-1 min-w-48"><Input aria-label="Buscar no resumo" value={summarySearch} onChange={e=>setSummarySearch(e.target.value)} placeholder="Buscar contato ou closer" startAdornment={<Search/>} size="lg"/></div><div className="w-48"><Choice label="Mostrar" id="summary-type" value={summaryType} options={['Todos','Agendamentos','Qualificados','Reagendamentos','Passadas','Não passadas','No-show']} onChange={setSummaryType}/></div></div>{summaryRows.length?<div className="overflow-x-auto"><table className="hod-table text-sm"><thead><tr><th>Contato</th><th>Criado em</th><th>Reunião em</th><th>Closer</th><th>Classificação</th></tr></thead><tbody>{summaryRows.map(c=><tr key={c.id}><td><Button color="primary" variant="ghost" opticallyAlign="start" onClick={()=>openDetail(c)}>{c.name}</Button><p className="text-xs text-secondary select-text">{c.phone}</p></td><td>{DateTime.fromISO(c.createdAt,{zone:'America/Sao_Paulo'}).toFormat('dd/MM/yyyy')}<p className="text-xs text-secondary">{DateTime.fromISO(c.createdAt,{zone:'America/Sao_Paulo'}).toFormat('HH:mm:ss')}</p></td><td>{DateTime.fromISO(c.date).toFormat('dd/MM/yyyy')}<p className="text-xs text-secondary">{c.time}</p></td><td><Badge color="discovery">{c.closer}</Badge></td><td><Badge>{c.qualified?'Qualificado':c.rescheduled?'Reagendamento':'Reunião comercial'}</Badge><div className="mt-2 flex flex-wrap gap-2">{meetingIds.has(c.id)&&<Badge>{c.passedToCloser?'Passada':'Não passada'}</Badge>}{c.googleStruck&&<Badge color="danger">No-show · riscada no Google</Badge>}</div></td></tr>)}</tbody></table></div>:<Empty title="Nenhum registro nesta base" description="Nenhum registro encontrado para a data e os filtros selecionados."/>}</Panel>
</>:page==='Analytics'?<>
<Panel className="space-y-4"><Segments label="Período de análise" value={range} options={['7 dias','30 dias','Todo histórico','Personalizado']} onChange={setRange}/><div className="grid sm:grid-cols-2 gap-4"><Choice label="Base" id="analytics-dimension" value={dimension} options={['Data da reunião','Data da criação']} onChange={setDimension}/><Choice label="Equipe" id="analytics-team" value={historyFilter} options={['Todos','Atuais','Antigos']} onChange={setHistoryFilter}/></div><MotionReveal>{range==='Personalizado'&&<div key="range" data-motion-content><p className="text-sm mb-2" id="analytics-range-label">Intervalo personalizado</p><DateRangePicker value={[DateTime.fromISO(from,{zone:'America/Sao_Paulo',locale:'pt-BR'}),DateTime.fromISO(to,{zone:'America/Sao_Paulo',locale:'pt-BR'})]} onChange={v=>{if(v){setFrom(v[0].toISODate()!);setTo(v[1].toISODate()!)}}} triggerDateFormat="dd LLL yyyy" size="lg" block={false}/></div>}</MotionReveal></Panel>
<MotionSwap identity={range+dimension+historyFilter+from+to} className="space-y-6"><p className="text-sm text-secondary">{range==='Todo histórico'?'Todo histórico sincronizado':range==='Personalizado'?`${from} a ${to}`:`${range} até ${date}`} · Google Calendar</p>
<div className="grid sm:grid-cols-3 gap-4"><Metric label="Agendamentos" value={imported?analytics.length:'—'} description="Volume no histórico sincronizado"/><Metric label="Closers" value={imported?ranking.length:'—'} description="Inclui antigos membros quando selecionados"/><Metric label="Dia com maior volume" value={analytics.length?Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0].slice(5).split('-').reverse().join('/'):'—'} description="Pela base de data selecionada"/></div>
<div className="grid xl:grid-cols-[1.2fr_1fr] gap-4"><Panel className="space-y-5"><Heading title="Volume de agendamentos" description={`${dimension} · histórico sincronizado`}><Badge>{analytics.length} registros</Badge></Heading>{orderedDays.length?<div className="space-y-5">{orderedDays.map(([d,n])=><div key={d} className="space-y-2"><div className="flex justify-between text-sm"><span>{DateTime.fromISO(d).toFormat('dd/MM/yyyy')}</span><strong>{n}</strong></div><Track value={n} max={Math.max(1,...Object.values(counts))} label={`Agendamentos em ${d}`}/></div>)}</div>:<Empty title="Sem agendamentos" description="Nenhum registro no período."/>}<p className="text-xs text-secondary">Agendamentos · sem inferir presença</p></Panel><Panel className="space-y-5"><Heading title="Ranking dos closers" description="Volume atribuído no período"/>{ranking.length?<ol className="space-y-5">{ranking.map((r,i)=><li key={r.name} className="flex gap-3 items-start"><span className="text-sm text-secondary w-5 pt-1">{i+1}</span><Avatar name={r.name} size={32}/><div className="flex-1 space-y-2"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-medium">{r.name}</span><strong className="text-sm">{r.count}</strong></div>{r.former&&<Badge>Antigo membro</Badge>}<Track value={r.count} max={Math.max(1,ranking[0].count)} label={`Volume de ${r.name}`}/></div></li>)}</ol>:<Empty title="Sem closers" description="Nenhum registro no filtro."/>}</Panel></div>
<Panel className="space-y-5"><Heading title="Volume por horário" description="Eventos sincronizados com horário válido"/><div className="grid grid-cols-3 sm:grid-cols-5 gap-4">{hourVolume.map(h=><div key={h.hour} className="space-y-2"><div className="flex justify-between text-xs"><span>{h.hour}</span><strong>{h.count}</strong></div><Track value={h.count} max={Math.max(1,...hourVolume.map(h=>h.count))} label={`Agendamentos às ${h.hour}`}/></div>)}</div></Panel>
<Alert variant="soft" color="info" title="Lacunas históricas" description={data?.historyCoverage||'Histórico ainda não sincronizado.'}/>
</MotionSwap></>:<>
<Segments label="Seção de configurações" value={settingsTab} options={['Geral','Google Agenda','Calendários','Sincronização']} onChange={setSettingsTab}/>
<MotionSwap identity={settingsTab}>{settingsTab==='Geral'?<div className="grid lg:grid-cols-2 gap-4"><Panel className="space-y-5"><Heading title="Aparência" description="Fundações e tipografia oficiais OpenAI Apps SDK UI"/><SegmentedControl aria-label="Aparência" value={theme} onChange={v=>setTheme(v)} size="lg"><SegmentedControl.Option value="light">Claro</SegmentedControl.Option><SegmentedControl.Option value="dark">Escuro</SegmentedControl.Option><SegmentedControl.Option value="system">Sistema</SegmentedControl.Option></SegmentedControl><p className="text-sm text-secondary">Claro, escuro ou acompanhar o sistema.</p><Switch label="Reduzir movimento" checked={motionPreference==='reduced'} onCheckedChange={v=>setMotionPreference(v?'reduced':'system')}/><p className="text-xs text-secondary">{reduceMotion?'Movimento reduzido ativo neste dispositivo.':'Transições oficiais ativas. A preferência de movimento reduzido do sistema é sempre respeitada.'}</p></Panel><Panel className="space-y-5"><Heading title="Preferências da operação" description="Preferências salvas no servidor"/><Choice label="Duração padrão" id="settings-duration" value={duration} options={['50','60']} onChange={v=>{setDuration(v);setSaved(false)}}/><p className="text-xs text-secondary">Duração em minutos; não altera reuniões existentes.</p><RadioGroup aria-label="Densidade" value={density} onChange={v=>{setDensity(v);setSaved(false);document.documentElement.dataset.density=v==='Compacta'?'compact':'comfortable'}}><RadioGroup.Item value="Confortável">Confortável</RadioGroup.Item><RadioGroup.Item value="Compacta">Compacta</RadioGroup.Item></RadioGroup><Switch label="Mostrar telefones nos cards" checked={showPhones} onCheckedChange={v=>{setShowPhones(v);onPhonesChange(v);setSaved(false)}}/><p className="text-xs text-secondary">O contato permanece nos detalhes.</p><div className="flex flex-wrap justify-between gap-2 text-sm"><span>Fuso horário</span><Badge>America/Sao_Paulo</Badge></div><Button color="primary" onClick={savePreferences}>{saved?'Preferências salvas':'Salvar preferências'}</Button></Panel></div>:<LiveSettings tab={settingsTab} data={data} notify={notify} reload={reload} sync={sync}/>}</MotionSwap>

</>}</MotionSwap>
}
