'use client';
import {useState} from 'react';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Select} from '@openai/apps-sdk-ui/components/Select';
import {Alert} from '@openai/apps-sdk-ui/components/Alert';
import {Panel,useHodTheme} from './apps-primitives';
type Result={status:string;message?:string;source?:string;readAt?:string;total?:number;pages?:number;calendars?:{id:string;summary:string}[];events?:{id:string;title:string;start?:{dateTime?:string;date?:string}}[]};
export default function GoogleProof({configured}:{configured:boolean}){
 const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[calendarId,setCalendar]=useState('');useHodTheme();
 async function read(){setBusy(true);try{const r=await fetch('/api/google/proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({calendarId:calendarId||undefined})});setResult(await r.json())}catch{setResult({status:'error',message:'Não foi possível consultar a conexão. Tente novamente.'})}finally{setBusy(false)}}
 return <div className="space-y-5"><form method="post" action="/api/google/start"><Button color="primary" type="submit" disabled={!configured}>Autorizar leitura do Google Agenda</Button></form><p className="text-sm text-secondary">A autorização Google é independente do acesso ao HOD Hub. A conexão é salva com segurança no servidor. Depois da autorização, abra o HOD Hub para sincronizar.</p><a className="text-link" href="/">Abrir HOD Hub e sincronizar</a><Panel className="space-y-4">{result?.calendars&&<div><p className="text-sm mb-2">Agenda</p><Select value={calendarId} options={[{value:'',label:'Primeira agenda com leitura de eventos'},...result.calendars.map(c=>({value:c.id,label:c.summary}))]} TriggerView={o=><><span className="sr-only">Agenda: </span>{o.label}</>} onChange={o=>setCalendar(o.value)} size="lg"/></div>}<Button color="primary" variant="outline" disabled={!configured||busy} onClick={read}>{busy?'Consultando Google…':'Provar leitura real'}</Button></Panel>{result&&<section className="space-y-4" role="status">{result.status==='success'?<><Alert variant="soft" color="success" title="Leitura real concluída" description={`${result.total} eventos · ${result.pages} páginas`}/><p className="text-sm text-secondary">Fonte: Google Calendar · {result.readAt} · sem persistência</p><Panel className="divide-y divide-default">{result.events?.map(e=><div className="py-3 text-sm space-y-1" key={e.id}><p className="font-medium">{e.title}</p><p className="text-secondary">{e.start?.dateTime||e.start?.date}</p></div>)}</Panel></>:<Alert variant="soft" color="danger" title="Leitura não concluída" description={result.message}/>}</section>}</div>
}
