'use client';
import {useState} from 'react';
import {DateTime} from 'luxon';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Menu} from '@openai/apps-sdk-ui/components/Menu';
import {Download} from '@openai/apps-sdk-ui/components/Icon';
import {Alert} from '@openai/apps-sdk-ui/components/Alert';
import {Badge} from '@openai/apps-sdk-ui/components/Badge';
import {SegmentedControl} from '@openai/apps-sdk-ui/components/SegmentedControl';
import {DateRangePicker} from '@openai/apps-sdk-ui/components/DateRangePicker';
import {EmptyMessage} from '@openai/apps-sdk-ui/components/EmptyMessage';
import {Panel,Choice} from './apps-primitives';
import {MotionSwap} from './apps-motion';
import type {HistoricalAnalytics} from '@/lib/historical-analytics';
function Segments({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div className="overflow-x-auto"><SegmentedControl aria-label={label} value={value} onChange={onChange}>{options.map(v=><SegmentedControl.Option value={v} key={v}>{v}</SegmentedControl.Option>)}</SegmentedControl></div>}
function Bars({rows}:{rows:{name:string;count:number;former?:boolean;formerLabel?:string;incomplete?:boolean}[]}){const max=Math.max(1,...rows.map(r=>r.count));return <ol className="space-y-4">{rows.map((r,i)=><li key={r.name}><div className="flex justify-between items-center gap-3 text-sm mb-2"><span>{i+1}. {r.name} {r.former&&<Badge color="secondary">{r.formerLabel||'Antigo membro'}</Badge>}</span><strong className="tabular-nums">{r.count===0&&r.incomplete?'Cobertura pendente':r.count.toLocaleString('pt-BR')}</strong></div><div className="h-3 rounded-full bg-surface-tertiary overflow-hidden"><div className="h-full bg-info-solid rounded-full hod-meter-fill" style={{transform:`scaleX(${r.count/max})`}}/></div></li>)}</ol>}
function Line({rows}:{rows:{name:string;count:number}[]}){const max=Math.max(1,...rows.map(r=>r.count));let gap=true;const points=rows.map((r,i)=>{if(!r.count){gap=true;return ''}const command=gap?'M':'L';gap=false;return `${command}${35+i*530/Math.max(1,rows.length-1)},${160-r.count/max*130}`}).join(' ');return <div><svg viewBox="0 0 600 200" className="w-full text-info" role="img" aria-label={`Agendamentos por mês: ${rows.map(r=>`${r.name}: ${r.count}`).join('; ')}`}><path d="M35 20V160H565" fill="none" stroke="currentColor" opacity=".25"/><path d={points} stroke="currentColor" strokeWidth="3" fill="none" strokeLinejoin="round"/>{rows.map((r,i)=><g key={r.name}>{r.count>0&&<circle cx={35+i*530/Math.max(1,rows.length-1)} cy={160-r.count/max*130} r="4" fill="currentColor"/>}<text x={35+i*530/Math.max(1,rows.length-1)} y="188" textAnchor="middle" fontSize="12" fill="currentColor">{r.name.slice(0,3)}</text></g>)}</svg><div className="flex flex-wrap gap-x-4 gap-y-2 text-xs text-secondary">{rows.map(r=><span key={r.name}>{r.name}: <strong>{r.count===0?'Nenhum novo lead nesta base':r.count}</strong></span>)}</div></div>}
export function HistoricalDashboard({data}:{data?:HistoricalAnalytics}){
const today=DateTime.now().setZone('America/Sao_Paulo').toISODate()!;
const [dimension,setDimension]=useState('Data da criação'),[period,setPeriod]=useState('Desde janeiro de 2026'),[from,setFrom]=useState('2026-01-01'),[to,setTo]=useState(today),[team,setTeam]=useState('Todos'),[rankView,setRankView]=useState('Barras'),[monthView,setMonthView]=useState('Barras'),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
const start=period==='Personalizado'?from:'2026-01-01',end=period==='Personalizado'?to:today;
const records=(data?.records||[]).filter(r=>{const d=dimension==='Data da criação'?r.created:r.date;return d>=start&&d<=end&&(team==='Todos'||(team==='Antigos'?(r.credits||[{former:r.former}]).some(c=>c.former):(r.credits||[{former:r.former}]).some(c=>!c.former)))});
const ranked=new Map<string,{name:string;count:number;former:boolean;formerLabel:string}>();for(const r of records){if(r.attribution!=='verified')continue;for(const c of r.credits||[{name:r.closer,former:r.former,formerLabel:r.formerLabel}]){if(team==='Antigos'&&!c.former||team==='Atuais'&&c.former)continue;const v=ranked.get(c.name)||{name:c.name,count:0,former:c.former,formerLabel:c.formerLabel};v.count++;ranked.set(c.name,v)}}const ranking=[...ranked.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
const months=new Map<string,number>();for(let m=DateTime.fromISO(start).startOf('month');m.toISODate()!<=end;m=m.plus({months:1})){months.set(m.toFormat('yyyy-MM'),0);if(months.size>120)break}for(const r of records){const m=(dimension==='Data da criação'?r.created:r.date).slice(0,7);months.set(m,(months.get(m)||0)+1)}
const chronological=[...months].sort(([a],[b])=>a.localeCompare(b)).map(([date,count])=>({name:DateTime.fromISO(date+'-01',{locale:'pt-BR'}).toFormat('LLL/yyyy'),count,incomplete:!data?.coverage.personalConnected||!data?.coverage.complete||count===0&&Boolean(data?.coverage.sourceMonths?.some(s=>s.month===date&&(dimension==='Data da criação'?s.created:s.meetings)>0))}));const monthRanking=[...chronological].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));const review=records.filter(r=>r.attribution==='review').length;
async function download(format:string){setExporting(true);setExportError('');try{const query=new URLSearchParams({format,from:start,to:end,dimension:dimension==='Data da criação'?'creation':'meeting',team:team==='Todos'?'all':team==='Antigos'?'former':'current'});const response=await fetch('/api/analytics/export?'+query.toString(),{signal:AbortSignal.timeout(90000)});if(!response.ok){const error=await response.json() as {message?:string};throw new Error(error.message||'Não foi possível exportar.')}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=response.headers.get('Content-Disposition')?.match(/filename="([^" ]+)"/)?.[1]||'hod-hub-exportacao';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setExportError((e as Error).message)}finally{setExporting(false)}}
if(!data)return <Alert color="info" title="Preparando o histórico" description="A análise precisa da leitura da sua agenda principal. Nenhum total anterior será apresentado como validado."/>;
return <div className="space-y-6"><div className="flex flex-wrap justify-between items-center gap-3"><p className="text-sm text-secondary">Dados verificáveis · histórico por pessoa</p><Menu><Menu.Trigger><Button color="primary" variant="outline" disabled={exporting}><Download/>{exporting?'Preparando arquivo…':'Exportar dados'}</Button></Menu.Trigger><Menu.Content align="end">{[['xlsx','Excel · todas as abas'],['csv','CSV · agendamentos'],['ranking','CSV · ranking dos closers'],['months','CSV · volume mensal'],['json','JSON · dados e metodologia']].map(([format,label])=><Menu.Item key={format} onSelect={()=>void download(format)}>{label}</Menu.Item>)}</Menu.Content></Menu></div>{exportError&&<Alert color="danger" description={exportError}/>}<Alert color={data.coverage.complete&&data.coverage.personalConnected?'info':'warning'} title={data.coverage.personalConnected?'Seu histórico de agendamentos':'Histórico parcial · conta pessoal pendente'} description={`Contas lidas: ${data.coverage.accounts.join(', ')||'nenhuma'}. ${data.coverage.complete?'Leitura das agendas próprias concluída.':'Importação da agenda principal em andamento.'} ${!data.coverage.personalConnected?'A conta Gmail pessoal ainda não foi conferida integralmente; o total não representa toda a sua trajetória.':''}`}/>
<p className="text-xs text-secondary">Suas contas consideradas: {data.coverage.authorAccounts.join(', ')}. Contas informadas por você e identidade da conexão; convites em agendas compartilhadas não comprovam cobertura integral dessas contas.</p><Panel className="space-y-4"><Segments label="Período histórico" value={period} options={['Desde janeiro de 2026','Personalizado']} onChange={setPeriod}/><div className="grid sm:grid-cols-2 gap-4"><Choice label="Base de contagem" id="historical-dimension" value={dimension} options={['Data da criação','Data da reunião']} onChange={setDimension}/><Choice label="Equipe" id="historical-team" value={team} options={['Todos','Atuais','Antigos']} onChange={setTeam}/></div>{period==='Personalizado'&&<DateRangePicker value={[DateTime.fromISO(from,{locale:'pt-BR'}),DateTime.fromISO(to,{locale:'pt-BR'})]} onChange={v=>{if(v){setFrom(v[0].toISODate()!);setTo(v[1].toISODate()!)}}} triggerDateFormat="dd LLL yyyy"/>}<p className="text-xs text-secondary">{dimension==='Data da criação'?'Quando o evento foi criado no Google, incluindo reuniões marcadas para depois.':'Quando a reunião foi marcada para ocorrer; não indica comparecimento.'} · America/Sao_Paulo · {start} a {end}</p></Panel>
<MotionSwap identity={dimension+period+from+to+team} className="space-y-6"><div className="grid sm:grid-cols-3 gap-4">{[['Agendamentos',records.length,'Leads únicos · consultoria ou participação comprovada'],['Closers identificados',ranking.length,'Atuais e antigos closers no período'],['Melhor mês disponível',monthRanking[0]?.count?monthRanking[0].name:'—',monthRanking[0]?.count?`${monthRanking[0].count} agendamentos`:'Sem registros']].map(([label,value,detail])=><Panel key={label}><p className="text-sm text-secondary">{label}</p><p className="heading-xl my-3 tabular-nums">{data.coverage.complete?typeof value==='number'?value.toLocaleString('pt-BR'):value:'—'}</p><p className="text-xs text-secondary">{detail}</p></Panel>)}</div>
{review>0&&<Alert color="warning" title={`${review} agendamentos com closer em revisão`} description="Entram no volume, mas ficam fora do ranking. Veja abaixo o convite e o motivo exato da pendência."/>}
<div className="grid xl:grid-cols-2 gap-4"><Panel className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="heading-sm">Ranking dos closers</h2><Segments label="Visualização do ranking" value={rankView} options={['Barras','Tabela']} onChange={setRankView}/></div>{ranking.length?rankView==='Barras'?<Bars rows={ranking}/>:<div className="overflow-x-auto"><table className="hod-table text-sm"><thead><tr><th>Posição</th><th>Closer</th><th>Agendamentos</th></tr></thead><tbody>{ranking.map((r,i)=><tr key={r.name}><td>{i+1}</td><td>{r.name} {r.former&&<Badge>{r.formerLabel||'Antigo membro'}</Badge>}</td><td>{r.count}</td></tr>)}</tbody></table></div>:<EmptyMessage><EmptyMessage.Title>Nenhum closer identificado neste filtro</EmptyMessage.Title></EmptyMessage>}<p className="text-xs text-secondary">Cada lead conta uma vez no total, mesmo com reagendamentos. Cada closer associado recebe um crédito por lead; a soma pode superar o total.</p></Panel>
<Panel className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="heading-sm">Volume por mês</h2><Segments label="Gráfico mensal" value={monthView} options={['Barras','Linha']} onChange={setMonthView}/></div>{monthView==='Barras'?<Bars rows={chronological}/>:<Line rows={chronological}/>}<p className="text-xs text-secondary">{dimension} · meses em ordem cronológica</p></Panel></div>
<Panel className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="heading-sm">Meses com mais agendamentos</h2>{(!data.coverage.complete||!data.coverage.personalConnected)&&<Badge color="warning">Cobertura parcial · todos os meses</Badge>}</div><Bars rows={monthRanking}/><p className="text-xs text-secondary">Cada lead fica no mês da primeira criação registrada (ou da primeira reunião, na base de reunião). Reagendamentos não voltam a contar em outros meses. O mês atual está em andamento.</p></Panel>{review>0&&<Panel className="space-y-4"><h2 className="heading-sm">Agendamentos em revisão</h2><p className="text-sm text-secondary">Estes são os registros que faltam atribuir. Não estimamos o closer quando o convite é ambíguo.</p><div className="overflow-x-auto"><table className="hod-table text-sm"><thead><tr><th>Contato</th><th>Reunião</th><th>Pendência</th><th>Convidados</th></tr></thead><tbody>{records.filter(r=>r.attribution==='review').map(r=><tr key={r.id}><td className="select-text">{r.name}</td><td>{r.date}<br/>{r.time}</td><td>{r.reviewReason}</td><td className="select-text break-all">{r.participants.join(', ')}</td></tr>)}</tbody></table></div></Panel>}
<Alert color="info" title="Como este histórico é contado" description={`Inclui eventos com Consultoria no título, mesmo sem seus e-mails no convite, conforme sua regra para o GoHighLevel; inclui também eventos antigos com sua autoria ou participação + closer + lead. Reuniões internas, eventos de outros SDRs já identificados e eventos sem closer ou lead são excluídos. Nomes iguais são unificados (maiúsculas, acentos e espaços não separam pessoas): ${data.coverage.duplicateLeads||0} repetições removidas. O mês usa a primeira criação registrada. Cada closer associado recebe um único crédito por lead. ${data.coverage.withoutCreated} leads sem criação verificável ficam fora da base de criação. Cancelamentos preservados contam como agendamentos feitos. Não há métricas de presença nesta análise. Eventos apagados antes da conexão não são reconstruídos.`}/></MotionSwap></div>
}
