'use client';
import {useState} from 'react';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Badge} from '@openai/apps-sdk-ui/components/Badge';
import {Checkbox} from '@openai/apps-sdk-ui/components/Checkbox';
import {Alert} from '@openai/apps-sdk-ui/components/Alert';
import {Panel} from './apps-primitives';
import {postApi,type HubData} from '@/lib/hub-types';
export function LiveSettings({tab,data,notify,reload,sync}:{tab:string;data:HubData|null;notify:(s:string)=>void;reload:()=>Promise<void>;sync:()=>void}){
const [ids,setIds]=useState<string[]|null>(null),[busy,setBusy]=useState(false);const selected=ids||data?.calendars.filter(c=>c.selected).map(c=>c.id)||[];
async function action(path:string,body:unknown,message:string){setBusy(true);try{await postApi(path,body);await reload();notify(message);setIds(null)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
if(tab==='Google Agenda')return <Panel className="space-y-5 max-w-3xl"><div className="flex justify-between"><h2 className="heading-sm">Google Agenda</h2><Badge color={data?.connection==='connected'?'success':'warning'}>{data?.connection==='connected'?'Conectado':'Conexão necessária'}</Badge></div><p className="text-sm text-secondary">A autorização Google é independente do login do HOD Hub. Leitura das agendas; nenhuma alteração dos eventos no Google.</p><form method="post" action="/api/google/start"><Button type="submit" color="primary">{data?.connection==='connected'?'Renovar conexão contínua':'Conectar Google'}</Button></form><Alert variant="soft" color="info" description="A conexão contínua permite renovar o acesso no servidor e sincronizar mesmo com seu computador desligado."/></Panel>;
if(tab==='Calendários')return <Panel className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="heading-sm">Calendários da operação</h2><Button variant="outline" color="primary" disabled={busy} onClick={()=>action('/api/calendars',{discover:true},'Lista de agendas atualizada')}>Atualizar agendas</Button></div>{!data?.calendars.length&&<p className="text-sm text-secondary">Conecte o Google para carregar suas agendas.</p>}<div className="divide-y divide-default">{data?.calendars.map(c=><div key={c.id} className="py-4 flex flex-wrap justify-between gap-3"><Checkbox disabled={!['owner','reader','writer'].includes(c.role)||busy} label={`${c.closer} · ${c.name}`} checked={selected.includes(c.id)} onCheckedChange={v=>setIds(v?[...selected,c.id]:selected.filter(id=>id!==c.id))}/><Badge>{({active:'Ativo',former:'Antigo membro',sdr:'SDR',unknown:'Identificação pendente'} as Record<string,string>)[c.team_status]||c.team_status}</Badge></div>)}</div><p className="text-sm text-secondary">Desmarcar uma agenda suspende novas leituras e preserva seu histórico. Agendas sem closer identificado não entram na capacidade dos closers.</p><Button disabled={busy||!ids} color="primary" onClick={()=>action('/api/calendars',{ids:selected},'Seleção salva no servidor')}>Salvar seleção</Button></Panel>;
return <div className="space-y-4"><Panel className="space-y-5"><h2 className="heading-sm">Sincronização</h2><p className="text-sm text-secondary">Atualização automática em ciclos de 10 segundos enquanto a tela está ativa, e ao voltar ao aplicativo. O tempo final depende da resposta do Google e das agendas. Sem conexão, os registros salvos são preservados e as tentativas são retomadas automaticamente. Com o aplicativo fechado, uma tarefa em nuvem está programada a cada hora, o intervalo mínimo suportado pelo Sites.</p><Button color="primary" onClick={sync}>Sincronizar agora</Button><div className="divide-y divide-default">{data?.calendars.filter(c=>c.selected).map(c=><div key={c.id} className="py-3 text-sm"><p className="font-medium">{c.closer}</p><p className="text-secondary">{c.error|| (c.syncing?'Importação em andamento':c.last_sync?`Atualizada: ${new Date(c.last_sync).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}`:'Aguardando primeira sincronização')}</p></div>)}</div></Panel><Alert color="info" variant="soft" title="Cobertura histórica" description={data?.historyCoverage||'Conecte as agendas para consultar a cobertura.'}/></div>;
}
