import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const connections=sqliteTable('google_connections',{owner:text('owner').primaryKey(),tokens:text('tokens').notNull(),expires:integer('expires').notNull(),connectedAt:text('connected_at').notNull(),status:text('status').notNull().default('connected')});
export const calendars=sqliteTable('calendars',{owner:text('owner').notNull(),id:text('id').notNull(),name:text('name').notNull(),role:text('role').notNull(),closer:text('closer').notNull(),teamStatus:text('team_status').notNull(),selected:integer('selected').notNull().default(0),syncToken:text('sync_token'),pageToken:text('page_token'),generation:text('generation'),mode:text('mode'),lastSync:text('last_sync'),error:text('error'),leaseUntil:integer('lease_until').notNull().default(0),lease:text('lease'),connectionAccount:text('connection_account'),coverageFrom:text('coverage_from'),coverageTo:text('coverage_to')},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const events=sqliteTable('google_events',{owner:text('owner').notNull(),calendarId:text('calendar_id').notNull(),googleId:text('google_id').notNull(),canonicalId:text('canonical_id').notNull(),generation:text('generation').notNull(),deleted:integer('deleted').notNull().default(0),title:text('title').notNull(),name:text('name'),phone:text('phone'),createdAt:text('created_at'),startsAt:text('starts_at'),endsAt:text('ends_at'),date:text('date'),kind:text('kind').notNull(),qualified:integer('qualified').notNull(),blocking:integer('blocking').notNull(),raw:text('raw').notNull()},t=>[primaryKey({columns:[t.owner,t.calendarId,t.googleId]}),index('idx_events_owner_date').on(t.owner,t.date),index('idx_events_owner_kind').on(t.owner,t.kind),index('idx_events_owner_canonical').on(t.owner,t.canonicalId)]);
export const operational=sqliteTable('operational',{owner:text('owner').notNull(),id:text('id').notNull(),status:text('status'),note:text('note').notNull().default(''),revision:integer('revision').notNull().default(0)},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const history=sqliteTable('operational_history',{id:text('id').primaryKey(),owner:text('owner').notNull(),consultationId:text('consultation_id').notNull(),at:text('at').notNull(),action:text('action').notNull(),value:text('value').notNull(),requestId:text('request_id').notNull()},t=>[index('idx_history_owner_consultation').on(t.owner,t.consultationId),uniqueIndex('idx_history_owner_request').on(t.owner,t.requestId)]);
export const preferences=sqliteTable('preferences',{owner:text('owner').primaryKey(),json:text('json').notNull(),updatedAt:text('updated_at').notNull()});

export const googleAccounts=sqliteTable('google_accounts',{owner:text('owner').notNull(),account:text('account').notNull(),tokens:text('tokens').notNull(),expires:integer('expires').notNull(),connectedAt:text('connected_at').notNull(),status:text('status').notNull().default('connected')},t=>[primaryKey({columns:[t.owner,t.account]})]);
